export const ROUTES = {
  HOME: "/",
  MANAGEADMIN: "/quan-ly-admin",
  MANAGEUSER: "/quan-ly-user",
  MANAGEHDV: "/quan-ly-hdv",
  ACTIVEADMIN: "/active-tai-khoan/:token",
  MANAGEVOUCHER: "/quan-ly-ma-giam-gia",
  MANAGEBLOG: "/quan-ly-blog",
  BLOGDETAIL: "/quan-ly-blog/:id",
  THONGKE: "/thong-ke",
  DANGNHAP: "/dang-nhap",
  QLTOUR: "/quan-ly-tour",
  TOURDETAIL: "/quan-ly-tour/:id",
  HETHONG: "/he-thong",
  RUTTIEN: "/quan-ly-rut-tien",
  BAOCAOHDV: "/bao-cao-hdv",
  BAOCAOPOST: "/bao-cao-bai-viet",
};
